temp = "Hello World!"
print(temp)
print(len(temp))
print(temp.index("l"))
print(temp.count("l"))
print(temp[3:7])
print(temp[3:7:2])
print(temp[3:7:1])
print(temp[::-1])
print(temp.upper())
print(temp.lower())
print(temp.startswith("Hello"))
print(temp.endswith("asdfadsf"))
print(temp.split(" "))
